# Generated by Django 5.1.1 on 2024-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctors_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='fill_report',
            new_name='files_report',
        ),
    ]
