# Generated by Django 5.1.1 on 2024-11-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_fill_report_doctors_files_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='files_report',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='report',
        ),
        migrations.RemoveField(
            model_name='doctors',
            name='uploaded_at',
        ),
    ]
